import { AuthService } from "./auth";
import { ClientService } from "./client";
import { AddressService } from "./address";
import { CompanyService } from "./company";
import { TokenService } from "./token";
import { InvoiceService } from "./invoice";
import { UserService } from "./user";
import { PaymentService } from "./payment";
import { PaymentLinkService } from "./paymentLink";

export const authService = new AuthService();
export const clientService = new ClientService();
export const addressService = new AddressService();
export const companyService = new CompanyService();
export const tokenService = new TokenService();
export const invoiceService = new InvoiceService();
export const userService = new UserService();
export const paymentService = new PaymentService();
export const paymentLinkService = new PaymentLinkService();
